#:schema node_modules/wrangler/config-schema.json

name = "vibeanime"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Minification helps keep the worker size down
minify = true

[assets]
directory = ".open-next/assets"
binding = "ASSETS"
